### ISSUE TITLE
reticle.nvim problem

### ISSUE THREAD

**Issue by tummetott** [edwardbaeg/dotfiles#1]
hey

I've seen this comment in your dotfiles:
https://github.com/edwardbaeg/dotfiles/blob/fc599ffe8abbc74fd884562855fa503236aeefae/nvim/init.lua#L675

I pushed a new commit not long ago, can you check if this bug still exists?

x Tummetott

**Comment by edwardbaeg** [comment]
Hey! Thanks for reaching out.

Unfortunately, I am still seeing the issue. There is still a faint line that moves around / flashes when I interact with LazyGit using ToggleTerm.

![image](https://github.com/edwardbaeg/dotfiles/assets/35383701/8c4e0246-8fb7-48bf-986b-92ef962165b4)

**Comment by edwardbaeg** [comment]
I made these changes and will now continue to use your plugin. [b59f1f7](https://github.com/edwardbaeg/dotfiles/commit/b59f1f7fc84871ef9259117dd17a99e640cdbca7)

Thanks for developing it!
